name: Build macOS App
on: [workflow_dispatch]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyinstaller requests openai

      - name: Build macOS GUI App
        run: |
          pyinstaller --onefile --windowed transonly_V0.2.py \
            --name "TransBy" \
            --icon "app.icns" || true
          ls -R dist || true

      - name: Upload macOS App
        uses: actions/upload-artifact@v4
        with:
          name: macOS-App
          path: dist/**/*.app
